name: "CI"

on:
  pull_request:
  push:

jobs:
  coding-standards:
    name: "Coding standards"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: phive

      - name: "Install dependencies"
        run: make tools

      - name: "Check coding style"
        run: make cs-check

  static-code-analysis:
    name: "Static code analysis"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: phive

      - name: "Install tools with phive"
        run: make tools

      - name: "Install dependencies with composer"
        run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader

      - name: PHPStan
        run: make analyze

  tests:
    name: "Tests on PHP ${{ matrix.php-version }} ${{ matrix.prefer-lowest }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0', '8.1', '8.2', '8.3' ]
        prefer-lowest: ['', '--prefer-lowest --prefer-stable']
        coverage-driver: [ 'xdebug' ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: phive

      - name: "Install tools with phive"
        run: make tools

      - name: "Install dependencies"
        run: composer update ${{ matrix.prefer-lowest }} --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        run: make tests
